[package]
name = "rust_rayon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mimalloc = "0.1.39"
rayon = "1.8.0"
rustc_data_structures = "0.0.1"
serde =  { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
crossbeam = "0.8"

[profile.release]
lto = true
codegen-units = 1
